#!/usr/bin/env bash
set -euo pipefail
create(){ gh label create "$1" --color "$2" --description "$3" --force; }
create bug d73a4a "Something is broken"
create enhancement a2eeef "New feature or improvement"
create documentation 0075ca "Documentation"
create compatibility 5319e7 "Version/platform compatibility evidence"
create performance fbca04 "Measured performance or profiling"
create needs-triage d4c5f9 "Needs maintainer triage"
create blender ea7600 "Blender integration"
create bridge 7057ff "Direct MoonRay bridge"
create ipc 8b5cf6 "IPC/shared-memory/data transport"
create moonray 3c8dbc "MoonRay renderer/runtime"
create wsl2 2ea44f "WSL2/WSLg platform"
create scene-translation bfdadc "Blender to MoonRay scene translation"
create materials e99695 "Materials/textures/shaders"
create viewport c5def5 "Interactive viewport"
create render-output fef2c0 "F12/AOV/EXR/RenderResult"
create xpu ff9f1c "MoonRay XPU/GPU validation"
create hydra-reference c2e0c6 "Hydra/hdMoonray fallback/reference experiment"
create build 1d76db "Build/runtime toolchain"
create dependencies 0366d6 "Dependency update"
create github-actions 000000 "GitHub Actions"
create breaking-change b60205 "Breaking change"
create skip-changelog e4e669 "Do not include in release notes"
